spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 555808370904-t8bcal4k76lc89olai5b10r1nmgicjc7.apps.googleusercontent.com
            client-secret: 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
